import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Multilingual string dictionaries supporting English, Hindi, and 5 North-Eastern Regional languages:
/// - Assamese (অসমীয়া)
/// - Bengali (বাংলা - Tripura / Barak Valley)
/// - Bodo (बर'/बड़ो - Bodoland, Assam)
/// - Manipuri (মৈতৈলোন্ / Meiteilon - Manipur)
/// - Mizo (Mizo ṭawng - Mizoram)
class AppStrings {
  AppStrings._();

  static const String _prefLanguageKey = 'selected_language';
  static String currentLanguage = 'en';
  static final ValueNotifier<String> languageNotifier = ValueNotifier<String>('en');

  static const Map<String, Map<String, String>> _localizedValues = {
    // ══════════════════════════════════════════════════════════
    // ENGLISH
    // ══════════════════════════════════════════════════════════
    'en': {
      'app_title': 'Smriti',
      'tagline': 'Gentle care, every day',
      'start_button': 'Start',
      'role_caregiver': 'I am a Caregiver',
      'role_patient': 'Continue as Patient',
      'offline_note': 'Works completely offline. Activity data stays private.',
      'caregiver_present_q': 'Is a caregiver with you right now?',
      'yes_together': 'Yes, we are together',
      'no_independent': 'No, independent session',
      'todays_journey': "Today's Gentle Journey",
      'daily_greeting': 'Welcome back. Let us spend a peaceful moment together.',
      'spoken_help': 'Listen to instruction',
      'pause': 'Pause',
      'resume': 'Resume',
      'take_time': "That's okay. We can take our time.",
      'gentle_success': 'Wonderful effort today!',
      'together_mode': 'Together Mode',
      'hint_for_caregiver': 'Caregiver Prompt Guide',
      'voice_feedback_prompt': 'Tap microphone to speak your observation',
      'voice_input_tip': 'Tap microphone to speak or type manually below',
      'voice_listening': 'Listening to your voice... (tap to finish)',
      'voice_recorded': 'Voice message recorded successfully',
      'non_medical_disclaimer': 'These are supportive engagement trends, not a medical diagnosis or staging assessment.',
      'caregiver_welcome_title': 'Create a Profile',
      'caregiver_welcome_badge': '5 minutes ❤️',
      'caregiver_welcome_desc': 'You know your loved one best. Tell us a little about them, and we will make every moment in this app feel familiar and comforting.',
      'caregiver_why_title': 'What this helps with:',
      'caregiver_why_1': 'Their favourite music, places, and foods will feel familiar.',
      'caregiver_why_2': 'Activities will move at their own comfortable pace.',
      'caregiver_why_3': 'Doctor notes and daily routines are always close by.',
      'start_profile_btn': 'Create Profile',
      'load_demo_btn': 'Load Demo Profile (Bonti Baruah)',
      'part_1_title': 'Part 1 of 3: General Information',
      'part_1_desc': 'Who are we caring for? Speak or type their details.',
      'part_2_title': 'Part 2 of 3: Abilities, Preferences & Observations',
      'part_2_desc': 'Sensory comforts, beloved music, foods, and calming triggers.',
      'part_3_title': "Part 3 of 3: Daily Routines & Doctor's Advises",
      'part_3_desc': 'Daily rhythm anchors, doctor recommendations, and voice reminders.',
      'profile_complete_title': 'Profile Created with Love!',
      'profile_complete_subtitle': "We are ready to begin today's peaceful journey.",
      'start_todays_journey': "Start Today's Journey",
      'fetching_profile': 'Welcome back! Fetching personalized journey...',
      'patient_name_label': 'Preferred Name or Nickname',
      'hometown_label': 'Familiar Hometown or Region',
      'doctor_advises_label': "Doctor's Advises & Clinician Notes",
      'routines_label': 'Daily Routines & Peaceful Anchors',
      'caregiver_obs_label': 'Caregiver Observations & Calming Anchors',
      'domain_memory': 'Remember',
      'domain_attention': 'Notice',
      'domain_language': 'Talk',
      'domain_executive': 'Plan & Sort',
      'domain_orientation': 'Today & Places',
      'domain_visuospatial': 'Explore & Match',
      'cg_domain_memory': 'Memory & Recognition',
      'cg_domain_attention': 'Attention & Focus',
      'cg_domain_language': 'Language & Communication',
      'cg_domain_executive': 'Executive Function',
      'cg_domain_orientation': 'Orientation & Context',
      'cg_domain_visuospatial': 'Visuospatial Skills',
      'memory_vault': 'Personal Memory Space',
      'add_memory': 'Add a Memory',
      'system_states': 'System & AI States',
      'session_finish': 'Finish Session for Today',
      'continue_button': 'Continue',
      'back_button': 'Go Back Safely',
    },

    // ══════════════════════════════════════════════════════════
    // HINDI
    // ══════════════════════════════════════════════════════════
    'hi': {
      'app_title': 'स्मृति साथी',
      'tagline': 'सद्भाव, अपनत्व और दैनिक संज्ञान सहयोग',
      'start_button': 'शुरू करें',
      'role_caregiver': 'मैं देखभालकर्ता (केयरगिवर) हूँ',
      'role_patient': 'मरीज के रूप में आगे बढ़ें',
      'offline_note': 'बिना इंटरनेट के भी पूर्णतः सुरक्षित चलता है।',
      'caregiver_present_q': 'क्या देखभालकर्ता अभी आपके साथ हैं?',
      'yes_together': 'हाँ, हम साथ हैं',
      'no_independent': 'नहीं, अकेले कर रहे हैं',
      'todays_journey': 'आज का शांत सफर',
      'daily_greeting': 'नमस्ते! आइए मिलकर कुछ सुखद पल बिताएं।',
      'spoken_help': 'निर्देश सुनें',
      'pause': 'विराम',
      'resume': 'पुनः शुरू करें',
      'take_time': 'कोई जल्दी नहीं है, आराम से करें।',
      'gentle_success': 'बहुत सुंदर प्रयास!',
      'together_mode': 'साथ-साथ मोड',
      'hint_for_caregiver': 'केयरगिवर संकेत मार्गदर्शिका',
      'voice_feedback_prompt': 'माइक दबाकर अपनी बात रिकॉर्ड करें',
      'voice_input_tip': 'बोलने के लिए माइक दबाएं, या नीचे टाइप करें',
      'voice_listening': 'आपकी आवाज सुनी जा रही है... (पूरा होने पर टैप करें)',
      'voice_recorded': 'वॉइस संदेश सफलतापूर्वक रिकॉर्ड हुआ',
      'non_medical_disclaimer': 'यह केवल दैनिक गतिविधि और जुड़ाव का ब्योरा है, कोई चिकित्सकीय निदान नहीं।',
      'caregiver_welcome_title': 'प्रोफाइल बनाएं',
      'caregiver_welcome_badge': 'केयरगिवर सेटअप • केवल 5 मिनट',
      'caregiver_welcome_desc': 'परिवार के देखभालकर्ता द्वारा केवल 5 मिनट में प्रोफाइल तैयार करें ताकि आपके प्रियजन को सबसे सहज, सुरक्षित और आनंददायक अनुभव मिले।',
      'caregiver_why_title': 'यह आपके प्रियजन की कैसे मदद करता है:',
      'caregiver_why_1': 'पसंदीदा संगीत, तस्वीरें और सांस्कृतिक यादों को जोड़ता है।',
      'caregiver_why_2': 'बिना किसी तनाव के सोचने और छूने की गति को आसान बनाता है।',
      'caregiver_why_3': 'दिनचर्या और डॉक्टर की सलाह को सुरक्षित रखता है।',
      'start_profile_btn': '5 मिनट में प्रोफाइल शुरू करें',
      'load_demo_btn': 'डेमो प्रोफाइल लोड करें (बोंती बरुआ)',
      'part_1_title': 'भाग 1 / 3: सामान्य जानकारी',
      'part_1_desc': 'हम किसकी देखभाल कर रहे हैं? बोलें या टाइप करें।',
      'part_2_title': 'भाग 2 / 3: क्षमता, पसंद और अवलोकन',
      'part_2_desc': 'सहजता, पसंदीदा संगीत, भोजन और सुकून देने वाली बातें।',
      'part_3_title': 'भाग 3 / 3: दिनचर्या और डॉक्टर की सलाह',
      'part_3_desc': 'दैनिक दिनचर्या, डॉक्टर के सुझाव और वॉइस रिमाइंडर्स।',
      'profile_complete_title': 'प्रोफाइल प्यार से तैयार है!',
      'profile_complete_subtitle': 'हम आज का शांतिपूर्ण सफर शुरू करने के लिए तैयार हैं।',
      'start_todays_journey': 'आज का सफर शुरू करें',
      'fetching_profile': 'नमस्ते! आपका आज का सफर लोड हो रहा है...',
      'patient_name_label': 'पसंदीदा नाम या उपनाम',
      'hometown_label': 'परिचित गृहनगर या क्षेत्र',
      'doctor_advises_label': 'डॉक्टर की सलाह और निर्देश',
      'routines_label': 'दैनिक दिनचर्या और सुकून भरे पल',
      'caregiver_obs_label': 'केयरगिवर के अवलोकन और शांत करने वाले उपाय',
      'domain_memory': 'याद रखें',
      'domain_attention': 'ध्यान दें',
      'domain_language': 'बातचीत',
      'domain_executive': 'क्रम और व्यवस्था',
      'domain_orientation': 'आज का दिन और स्थान',
      'domain_visuospatial': 'मिलान और पहचान',
      'cg_domain_memory': 'स्मृति और पहचान',
      'cg_domain_attention': 'ध्यान और एकाग्रता',
      'cg_domain_language': 'भाषा और संवाद',
      'cg_domain_executive': 'कार्यकारी क्षमता',
      'cg_domain_orientation': 'समय व स्थान बोध',
      'cg_domain_visuospatial': 'दृश्य-स्थानिक कौशल',
      'memory_vault': 'व्यक्तिगत स्मृति संदूक',
      'add_memory': 'नई स्मृति जोड़ें',
      'system_states': 'सिस्टम और एआई स्थितियां',
      'session_finish': 'आज का सत्र समाप्त करें',
      'continue_button': 'आगे बढ़ें',
      'back_button': 'सुरक्षित पीछे जाएं',
    },

    // ══════════════════════════════════════════════════════════
    // NORTH-EAST 1: ASSAMESE (অসমীয়া - Assam)
    // ══════════════════════════════════════════════════════════
    'as': {
      'app_title': 'স্মৃতি সংগী',
      'tagline': 'মৰমৰ সান্নিধ্য আৰু দৈনন্দিন মানসিক সঁহাৰি',
      'start_button': 'আৰম্ভ কৰক',
      'role_caregiver': 'মই এজন শুশ্ৰূষাকাৰী (Caregiver)',
      'role_patient': 'অংশগ্ৰহণকাৰী হিচাপে আৰম্ভ কৰক',
      'offline_note': 'ইণ্টাৰনেট অবিহনে সম্পূৰ্ণ কাম কৰে। সকলো তথ্য নিজৰ ডিভাইচতে সুৰক্ষিত।',
      'caregiver_present_q': 'শুশ্ৰূষাকাৰী আপোনাৰ লগত উপস্থিত আছেনে?',
      'yes_together': 'হয়, আমি একেলগে আছোঁ',
      'no_independent': 'নহয়, অকলেই কৰিম',
      'todays_journey': 'আজিৰ শান্ত যাত্ৰা',
      'daily_greeting': 'স্বাগতম! আহক আমি একেলগে কেইটামান শান্তিপূৰ্ণ মুহূৰ্ত কটাওঁ।',
      'spoken_help': 'নিৰ্দেশনা শুনক',
      'pause': 'ৰওক',
      'resume': 'পুনৰ আৰম্ভ কৰক',
      'take_time': 'কোনো খৰখেদা নাই, শান্তভাৱে কৰক।',
      'gentle_success': 'বৰ সুন্দৰ প্ৰয়াস!',
      'together_mode': 'একত্ৰে খেলাৰ সুবিধা',
      'hint_for_caregiver': 'শুশ্ৰূষাকাৰীৰ বাবে সহায়ক ইঙ্গিত',
      'voice_feedback_prompt': 'কথা ক\'বলৈ মাইক্ৰ\'ফন স্পৰ্শ কৰক',
      'voice_input_tip': 'কথা ক\'বলৈ মাইক্ৰ\'ফন স্পৰ্শ কৰক বা লিখক',
      'voice_listening': 'আপোনাৰ কথা শুনা হৈছে... (শেষ হ\'লে স্পৰ্শ কৰক)',
      'voice_recorded': 'কণ্ঠ বাৰ্তা সফলতাৰে সংৰক্ষণ হ\'ল',
      'non_medical_disclaimer': 'এইয়া কেৱল দৈনন্দিন সঁহাৰি আৰু সংযোগৰ তথ্য, কোনো চিকিৎসাজনিত পৰীক্ষা নহয়।',
      'caregiver_welcome_title': 'এটা প্ৰোফাইল সৃষ্টি কৰক',
      'caregiver_welcome_badge': 'শুশ্ৰূষাকাৰী প্ৰস্তুতি • মাত্ৰ ৫ মিনিট',
      'caregiver_welcome_desc': 'পৰিয়ালৰ শুশ্ৰূষাকাৰীৰ দ্বাৰা মাত্ৰ ৫ মিনিটতে প্ৰোফাইল প্ৰস্তুত কৰক যাতে আপোনাৰ আপোনজনৰ বাবে সকলোতকেই শান্ত, সুৰক্ষিত আৰু আনন্দদায়ক অভিজ্ঞতা প্ৰদান কৰিব পাৰি।',
      'caregiver_why_title': 'ই আপোনাৰ আপোনজনক কেনেদৰে সহায় কৰিব:',
      'caregiver_why_1': 'অসম আৰু উত্তৰ-পূবৰ মৰমৰ গীত, ছবি আৰু স্মৃতিৰ সৈতে সংযোগ কৰে।',
      'caregiver_why_2': 'কোনো মানসিক চাপ নোহোৱাকৈ সহজ আৰু শান্ত গতিত খেলাৰ সুবিধা দিয়ে।',
      'caregiver_why_3': 'দৈনন্দিন নীতি-নিয়ম আৰু ডাক্তৰৰ পৰামৰ্শ অফলাইনত সুৰক্ষিত ৰাখে।',
      'start_profile_btn': '৫ মিনিটৰ প্ৰোফাইল আৰম্ভ কৰক',
      'load_demo_btn': 'ডেমো প্ৰোফাইল ব্যৱহাৰ কৰক (বন্টি বৰুৱা)',
      'part_1_title': 'ভাগ ১ / ৩: সাধাৰণ তথ্য',
      'part_1_desc': 'আমি কাৰ যত্ন লৈছোঁ? কথা কওক বা লিখি জনাওক।',
      'part_2_title': 'ভাগ ২ / ৩: ক্ষমতা, পছন্দ আৰু লক্ষ্যণ',
      'part_2_desc': 'প্ৰিয় সংগীত, খাদ্য, শান্তিপূৰ্ণ অনুভৱ আৰু যত্নৰ লক্ষ্যণ।',
      'part_3_title': 'ভাগ ৩ / ৩: দৈনন্দিন নিয়ম আৰু চিকিৎসকৰ পৰামৰ্শ',
      'part_3_desc': 'দৈনন্দিন ৰীতি-নীতি, ডাক্তৰৰ দিহা আৰু কণ্ঠ স্মাৰক।',
      'profile_complete_title': 'মৰমেৰে প্ৰোফাইল প্ৰস্তুত হ\'ল!',
      'profile_complete_subtitle': 'আমি আজিৰ শান্ত যাত্ৰা আৰম্ভ কৰিবলৈ সাজু।',
      'start_todays_journey': 'আজিৰ যাত্ৰা আৰম্ভ কৰক',
      'fetching_profile': 'স্বাগতম! আপোনাৰ বাবে আজিৰ যাত্ৰা প্ৰস্তুত কৰা হৈছে...',
      'patient_name_label': 'মৰমৰ নাম বা উপনাম',
      'hometown_label': 'চিনাকি গাঁও/চহৰ বা অঞ্চল',
      'doctor_advises_label': 'চিকিৎসকৰ পৰামৰ্শ আৰু দিহা',
      'routines_label': 'দৈনন্দিন নিয়ম আৰু শান্তিপূৰ্ণ সময়',
      'caregiver_obs_label': 'শুশ্ৰূষাকাৰীৰ লক্ষ্যণ আৰু শান্ত কৰাৰ উপায়',
      'domain_memory': 'মনত পেলাওক',
      'domain_attention': 'মনোযোগ দিয়ক',
      'domain_language': 'কথোপকথন',
      'domain_executive': 'সজাই তোলক',
      'domain_orientation': 'আজিৰ দিন আৰু পৰিৱেশ',
      'domain_visuospatial': 'আকৃতি আৰু সন্ধান',
      'cg_domain_memory': 'স্মৃতি আৰু চিনাক্তকৰণ',
      'cg_domain_attention': 'মনোযোগ আৰু দৃষ্টি',
      'cg_domain_language': 'ভাষা আৰু যোগাযোগ',
      'cg_domain_executive': 'কাৰ্য্যকৰী ক্ষমতা',
      'cg_domain_orientation': 'সময় আৰু স্থানবোধ',
      'cg_domain_visuospatial': 'স্থান আৰু দৃশ্যগত দক্ষতা',
      'memory_vault': 'ব্যক্তিগত স্মৃতি ভঁৰাল',
      'add_memory': 'নতুন স্মৃতি যোগ কৰক',
      'system_states': 'ছিষ্টেম আৰু এআই অৱস্থা',
      'session_finish': 'আজিৰ সত্ৰ সমাপ্ত কৰক',
      'continue_button': 'আগবাঢ়ক',
      'back_button': 'সুৰক্ষিতভাৱে পিছলৈ যাওক',
    },

    // ══════════════════════════════════════════════════════════
    // NORTH-EAST 2: BENGALI (বাংলা - Tripura & Barak Valley)
    // ══════════════════════════════════════════════════════════
    'bn': {
      'app_title': 'স্মৃতি সাথী',
      'tagline': 'প্রতিদিনের কোমল যত্ন ও সংযোগ',
      'start_button': 'শুরু করুন',
      'role_caregiver': 'আমি একজন সেবাদানকারী (কেয়ারগিভার)',
      'role_patient': 'প্রিয়জন হিসেবে শুরু করুন',
      'offline_note': 'ইন্টারনেট ছাড়াই সম্পূর্ণ অফলাইনে চলে। তথ্য নিরাপদ।',
      'caregiver_present_q': 'কেয়ারগিভার কি আপনার সাথে আছেন?',
      'yes_together': 'হ্যাঁ, আমরা একসাথে আছি',
      'no_independent': 'না, একাই করছি',
      'todays_journey': 'আজকের শান্ত যাত্রা',
      'daily_greeting': 'স্বাগতম! আসুন একসাথে শান্তিময় কিছু সময় কাটাই।',
      'spoken_help': 'নির্দেশনা শুনুন',
      'pause': 'থামুন',
      'resume': 'পুনরায় চালু করুন',
      'take_time': 'কোনো তাড়া নেই, ধীরে সুস্থে করুন।',
      'gentle_success': 'খুব সুন্দর প্রচেষ্টা!',
      'together_mode': 'একসাথে মোড',
      'hint_for_caregiver': 'কেয়ারগিভার সহায়ক নির্দেশনা',
      'voice_feedback_prompt': 'কথা বলতে মাইকে চাপ দিন',
      'voice_input_tip': 'মাইকে চাপ দিয়ে বলুন অথবা নিচে লিখুন',
      'voice_listening': 'আপনার কথা শোনা হচ্ছে... (শেষ হলে চাপ দিন)',
      'voice_recorded': 'কণ্ঠবার্তা সফলভাবে সংরক্ষিত হয়েছে',
      'non_medical_disclaimer': 'এটি কেবল প্রতিদিনের সংযোগ ও অনুভূতির রেকর্ড, কোনো চিকিৎসা নির্ণয় নয়।',
      'caregiver_welcome_title': 'একটি প্রোফাইল তৈরি করুন',
      'caregiver_welcome_badge': 'কেয়ারগিভার সেটআপ • মাত্র ৫ মিনিট',
      'caregiver_welcome_desc': 'আপনার প্রিয়জনকে সবচেয়ে সুন্দর ও আরামদায়ক অভিজ্ঞতা দিতে মাত্র ৫ মিনিটে প্রোফাইল প্রস্তুত করুন।',
      'caregiver_why_title': 'এটি যেভাবে সাহায্য করে:',
      'caregiver_why_1': 'প্রিয় গান, খাবার ও স্মৃতিকে যুক্ত করে।',
      'caregiver_why_2': 'চাপমুক্ত শান্ত গতিতে খেলার সুযোগ দেয়।',
      'caregiver_why_3': 'দৈনন্দিন রুটিন ও ডাক্তারের পরামর্শ নিরাপদে রাখে।',
      'start_profile_btn': '৫ মিনিটে প্রোফাইল তৈরি করুন',
      'load_demo_btn': 'ডেমো প্রোফাইল লোড করুন (বন্টি বরুয়া)',
      'part_1_title': 'পর্ব ১ / ৩: সাধারণ তথ্য',
      'part_1_desc': 'আমরা কার যত্ন নিচ্ছি? বলুন বা লিখুন।',
      'part_2_title': 'পর্ব ২ / ৩: সক্ষমতা, পছন্দ ও পর্যবেক্ষণ',
      'part_2_desc': 'প্রিয় গান, খাবার, স্বাচ্ছন্দ্য ও শান্ত করার উপায়।',
      'part_3_title': 'পর্ব ৩ / ৩: দৈনন্দিন রুটিন ও ডাক্তারের পরামর্শ',
      'part_3_desc': 'দৈনন্দিন নিয়ম, ডাক্তারের পরামর্শ ও ভয়েস রিমাইন্ডার।',
      'profile_complete_title': 'ভালবাসায় প্রোফাইল তৈরি হয়েছে!',
      'profile_complete_subtitle': 'আমরা আজকের শান্ত যাত্রা শুরু করতে প্রস্তুত।',
      'start_todays_journey': 'আজকের যাত্রা শুরু করুন',
      'fetching_profile': 'স্বাগতম! আপনার যাত্রা প্রস্তুত হচ্ছে...',
      'patient_name_label': 'প্রিয় নাম বা ডাকনাম',
      'hometown_label': 'পরিচিত শহর বা এলাকা',
      'doctor_advises_label': 'ডাক্তারের পরামর্শ ও নির্দেশনা',
      'routines_label': 'দৈনন্দিন রুটিন ও শান্ত মুহূর্ত',
      'caregiver_obs_label': 'কেয়ারগিভারের পর্যবেক্ষণ ও শান্ত রাখার উপায়',
      'domain_memory': 'স্মৃতিচারণ',
      'domain_attention': 'মনোযোগ',
      'domain_language': 'কথোপকথন',
      'domain_executive': 'পরিকল্পনা ও বিন্যাস',
      'domain_orientation': 'আজকের দিন ও স্থান',
      'domain_visuospatial': 'আকার ও মিল',
      'cg_domain_memory': 'স্মৃতি ও শনাক্তকরণ',
      'cg_domain_attention': 'মনোযোগ ও দৃষ্টি',
      'cg_domain_language': 'ভাষা ও যোগাযোগ',
      'cg_domain_executive': 'কার্যকরী সক্ষমতা',
      'cg_domain_orientation': 'সময় ও স্থানবোধ',
      'cg_domain_visuospatial': 'স্থান ও দৃশ্যগত দক্ষতা',
      'memory_vault': 'ব্যক্তিগত স্মৃতি ভাণ্ডার',
      'add_memory': 'নতুন স্মৃতি যোগ করুন',
      'system_states': 'সিস্টেম ও এআই অবস্থা',
      'session_finish': 'আজকের সেশন সমাপ্ত করুন',
      'continue_button': 'এগিয়ে যান',
      'back_button': 'নিরাপদে ফিরে যান',
    },

    // ══════════════════════════════════════════════════════════
    // NORTH-EAST 3: BODO (बर'/बड़ो - Bodoland, Assam)
    // ══════════════════════════════════════════════════════════
    'brx': {
      'app_title': 'स्मृति लोगो',
      'tagline': 'रोमै रोमै जोथोन आरो सानफ्रोमबोनि हेफाजब',
      'start_button': 'जागायदो',
      'role_caregiver': 'आं जोथोनगिरि (Caregiver)',
      'role_patient': 'मोजां मोनग्रा हिसाबै थांदो',
      'offline_note': 'इन्टारनेट गैयाबाबो मोजाङै चोले। गासै खोथाफोरा रैखाथि।',
      'caregiver_present_q': 'जोथोनगिरिया दा नोंथांनि लोगोआव दं नामा?',
      'yes_together': 'नंगौ, जों लोगोसे दं',
      'no_independent': 'नङा, हारसिं',
      'todays_journey': 'दिनैनि गोजोन जाथ्रा',
      'daily_greeting': 'बरायबाय! फै जों लोगोसे गोजोन सम खालामनि।',
      'spoken_help': 'बिथोन खोनासंदो',
      'pause': 'थाथो',
      'resume': 'फिन जागाय',
      'take_time': 'जेबो दावराव गैया, लिसिम-लिसिम खालाम।',
      'gentle_success': 'जोबोर मोजां नाजानाय!',
      'together_mode': 'लोगोसे मोड',
      'hint_for_caregiver': 'जोथोनगिरिनि हेफाजब दिन्थिनाय',
      'voice_feedback_prompt': 'बुंनो माइकआव थुदो',
      'voice_input_tip': 'बुंनो माइकआव थुदो एबा लिरदो',
      'voice_listening': 'नोंथांनि राव खोनासंगासिनो दं...',
      'voice_recorded': 'राव मोजाङै दोनों',
      'non_medical_disclaimer': 'बेयो खालि सानफ्रोमबोनि हेफाजबसो, फाहामथाय आनजाद नङा।',
      'caregiver_welcome_title': 'प्रफाइल सोरजिदो',
      'caregiver_welcome_badge': 'जोथोनगिरि थियारि • 5 मिनिट',
      'caregiver_welcome_desc': 'नोंथांनि अनसुला मानसिखौ सुबिदा होनो 5 मिनिटआव प्रफाइल बानायदो।',
      'caregiver_why_title': 'बेयो माबोरै हेफाजब होयो:',
      'caregiver_why_1': 'मोजां मोननाय मेथाय, जायगा आरो गोसोखांथि सोमोन्दो खालामो।',
      'caregiver_why_2': 'गावनि गोसोबायदि लिसिम गतिआव गेलेनो सुबिदा होयो।',
      'caregiver_why_3': 'डातारनि बिथोन आरो सानफ्रोमबोनि नियम रैखाथि लाखियो।',
      'start_profile_btn': '5 मिनिटआव प्रफाइल बानायदो',
      'load_demo_btn': 'डेमो प्रफाइल लादो (बन्ती बरुवा)',
      'part_1_title': 'बाहागो 1 / 3: सरासनस्रा मिथिसार',
      'part_1_desc': 'जों सोरनि जोथोन लादों? बुंदो एबा लिरदो।',
      'part_2_title': 'बाहागो 2 / 3: गोहो, मोजां मोननाय आरो नोजोर',
      'part_2_desc': 'मोजां मोननाय मेथाय, जानाय आरो गोजोन मोननाय।',
      'part_3_title': 'बाहागो 3 / 3: सानफ्रोमबोनि नियम आरो डातारनि बिथोन',
      'part_3_desc': 'सानफ्रोमबोनि नियम, डातारनि बिथोन आरो राव गोसोखांथि।',
      'profile_complete_title': 'अननायजों प्रफाइल सोरजिबाय!',
      'profile_complete_subtitle': 'जों दिनैनि गोजोन जाथ्रानि थाखाय थियारि।',
      'start_todays_journey': 'दिनैनि जाथ्रा जागायदो',
      'fetching_profile': 'बरायबाय! दिनैनि जाथ्रा लाबोगासिनो दं...',
      'patient_name_label': 'मोजां मोननाय मुं',
      'hometown_label': 'मिथिसार नोगोर एबा जायगा',
      'doctor_advises_label': 'डातारनि बिथोन आरो नेम',
      'routines_label': 'सानफ्रोमबोनि नेम आरो गोजोन सम',
      'caregiver_obs_label': 'जोथोनगिरिनि नोजोर आरो गोजोनहोग्रा',
      'domain_memory': 'गोसोखां',
      'domain_attention': 'गोसो होनाय',
      'domain_language': 'सावराय',
      'domain_executive': 'साजाय',
      'domain_orientation': 'दिनै आरो जायगा',
      'domain_visuospatial': 'नाय आरो मिलिनाय',
      'cg_domain_memory': 'गोसोखांथि आरो सिनायथि',
      'cg_domain_attention': 'गोसो होनाय आरो नोजोर',
      'cg_domain_language': 'राव आरो फोरावनाय',
      'cg_domain_executive': 'मावफुं गोहो',
      'cg_domain_orientation': 'सम आरो जायगानि गोसो',
      'cg_domain_visuospatial': 'जायगा आरो नुथाय गोहो',
      'memory_vault': 'गावनि गोसोखां बाकसु',
      'add_memory': 'गोदान गोसोखांथि दाजाब',
      'system_states': 'सिस्टेम आरो AI थाथाय',
      'session_finish': 'दिनैनि हाबा फोजोब',
      'continue_button': 'थां',
      'back_button': 'रैखाथियै उनफिन',
    },

    // ══════════════════════════════════════════════════════════
    // NORTH-EAST 4: MANIPURI (মৈতৈলোন্ / Meiteilon - Manipur)
    // ══════════════════════════════════════════════════════════
    'mni': {
      'app_title': 'স্মৃতি লোয়নবী',
      'tagline': 'নোংমগী নিংথিনা য়েন্থোকপা অমসুং নুংশি মরী',
      'start_button': 'হৌদোরকউ',
      'role_caregiver': 'ঐহাক য়েন্থোকপীনবা (Caregiver) নি',
      'role_patient': 'নুংশিরবা মীওই ওইনা চৎথরো',
      'offline_note': 'ইন্তর্নেত য়াওদনা মপুংফানা চৎপদা য়াই। লনাই পোৎশক মপুংফানা কনথোকই।',
      'caregiver_present_q': 'য়েন্থোকপীবগা পুন্না লৈবিরিব্রা?',
      'yes_together': 'হোই, পুন্না লৈরি',
      'no_independent': 'নত্তে, মশামকনি',
      'todays_journey': 'ঙসীবগী শান্তিবীরবা খোঙচৎ',
      'daily_greeting': 'তরাম্না ওকচরি! পুন্না নুংঙাইরবা কুন কয়া লেপমিন্নসি।',
      'spoken_help': 'তৌগদবা তাউ',
      'pause': 'লেপখরো',
      'resume': 'অমুক হন্না চৎথরো',
      'take_time': 'করিগুম্বা য়াওদে, নিংথিনা তৌবিয়ু।',
      'gentle_success': 'য়াম্না ফজরবা হোৎনবনি!',
      'together_mode': 'পুন্না শানবা মোদ',
      'hint_for_caregiver': 'য়েন্থোকপীবগী য়ারবা লমজিং',
      'voice_feedback_prompt': 'ৱা ঙাংনবগী মাইক নমবিয়ু',
      'voice_input_tip': 'ৱা ঙাংনবগী মাইক নমবিয়ু নত্রগা মখাদা ইরকউ',
      'voice_listening': 'নহাক্কী খোন্থোক তারি... (লোইরগা নমবিয়ু)',
      'voice_recorded': 'খোন্থোক্কী পাও নিংথিনা থমখ্রে',
      'non_medical_disclaimer': 'মসি নোংমগী হোৎনবা অমসুং পুনবগী ৱারোলনি, লায়েনগী নিংতম্বা নত্তে।',
      'caregiver_welcome_title': 'প্রোফাইল অমা শেম্মু',
      'caregiver_welcome_badge': 'য়েন্থোকপীবগী শেম-শাবা • মিনিট ৫ তৌই',
      'caregiver_welcome_desc': 'নহাক্কী নুংশিরবা মীওইদা খ্বাইদগী নুংঙাইবা ফীভম পীনবগীদমক মিনিট ৫ খক্তদা প্রোফাইল শেম্বীয়ু।',
      'caregiver_why_title': 'মসিনা করম্না মতেং ওইবগে:',
      'caregiver_why_1': 'পামজবা ঈশৈ, মফম অমসুং চিঞ্জাক মরী থম্মী।',
      'caregiver_why_2': 'ৱাখলদা ৱাহন্দনা মশাগী খোঙচৎতা শানবা য়াহল্লি।',
      'caregiver_why_3': 'নোংমগী চৎনবী অমসুং ডাক্তরগী পাউতাক নিংথিনা থম্মি।',
      'start_profile_btn': 'মিনিট ৫ গী প্রোফাইল হৌগদবনি',
      'load_demo_btn': 'দেমো প্রোফাইল শিজিন্নৌ (বোন্তি বরুৱা)',
      'part_1_title': 'শরুক ১ / ৩: মচাখায়গী পাউ',
      'part_1_desc': 'ঐখোয়না কনাবু য়েন্থোকপীরিবগে? ঙাঙলু নত্রগা ইরকউ।',
      'part_2_title': 'শরুক ২ / ৩: ঙম্বা, পামজবা অমসুং উবা',
      'part_2_desc': 'পামজবা ঈশৈ, চিঞ্জাক অমসুং নুংঙাইবগী মরী।',
      'part_3_title': 'শরুক ৩ / ৩: নোংমগী চৎনবী অমসুং ডাক্তরগী পাউতাক',
      'part_3_desc': 'নোংমগী চৎনবী, ডাক্তরগী লমজিং অমসুং খোন্থোক্কী নিংশিংবা।',
      'profile_complete_title': 'নুংশিবগা লোয়ননা প্রোফাইল শেম্লে!',
      'profile_complete_subtitle': 'ঐখোয়না ঙসীবগী শান্তিবীরবা খোঙচৎ হৌনবা শেম-শারে।',
      'start_todays_journey': 'ঙসীবগী খোঙচৎ হৌগদবনি',
      'fetching_profile': 'তরাম্না ওকচরি! ঙসীবগী খোঙচৎ শেম-শারি...',
      'patient_name_label': 'পামজবা মিং নত্রগা কৌনবা মিং',
      'hometown_label': 'খঙনরবা য়ুম নত্রগা মফম',
      'doctor_advises_label': 'ডাক্তরগী পাউতাক অমসুং লমজিং',
      'routines_label': 'নোংমগী চৎনবী অমসুং শান্তিবীরবা মতম',
      'caregiver_obs_label': 'য়েন্থোকপীবনা উবা অমসুং শান্তিবীরবা পাউতাক',
      'domain_memory': 'নিংশিংবা',
      'domain_attention': 'মিৎয়েং থম্বা',
      'domain_language': 'ৱারী শানবা',
      'domain_executive': 'শেমজিনবা',
      'domain_orientation': 'ঙসি অমসুং মফম',
      'domain_visuospatial': 'য়েংবা অমসুং চান্নবা',
      'cg_domain_memory': 'নিংশিংবা অমসুং শকখঙবা',
      'cg_domain_attention': 'মিৎয়েং অমসুং ৱাখল',
      'cg_domain_language': 'লোন অমসুং পাওফাওনবা',
      'cg_domain_executive': 'থবক ঙম্বগী শক্তি',
      'cg_domain_orientation': 'মতম অমসুং মফম খঙবা',
      'cg_domain_visuospatial': 'মফম অমসুং মশক খঙবা',
      'memory_vault': 'লনাইগী নিংশিংবা থুংশং',
      'add_memory': 'অনৌবা নিংশিংবা হাপচিল্লু',
      'system_states': 'সিস্তেম অমসুং AI ফীভম',
      'session_finish': 'ঙসীবগী থবক লোইশিনখরো',
      'continue_button': 'মাংলোয়দা চৎথরো',
      'back_button': 'নিংথিনা কননা হনলু',
    },

    // ══════════════════════════════════════════════════════════
    // NORTH-EAST 5: MIZO (Mizo ṭawng - Mizoram)
    // ══════════════════════════════════════════════════════════
    'lus': {
      'app_title': 'Smriti Companion',
      'tagline': 'Duat takin ni tin enkawlna',
      'start_button': 'Tan rawh',
      'role_caregiver': 'Enkawltu ka ni (Caregiver)',
      'role_patient': 'Damlo anga chhunzawmna',
      'offline_note': 'Internet tel loin a hman theih. Thil zawng zawng a him.',
      'caregiver_present_q': 'Enkawltu i kiangah an awm em?',
      'yes_together': 'Aw, kan awmdun e',
      'no_independent': 'Aih, mahniin ka ti',
      'todays_journey': 'Vawiin Hun Nuam tak',
      'daily_greeting': 'Chibai le! Vawiinah hun nuam tak hmangdun ang hmiang.',
      'spoken_help': 'Hrilhna ngaithla rawh' ,
      'pause': 'Chawl lawk rawh',
      'resume': 'Chhunzawm leh rawh',
      'take_time': 'Hmanhmawh a ngai lo, muangchangin ti rawh.',
      'gentle_success': 'I ti tha hle mai!',
      'together_mode': 'Tamdun Mode',
      'hint_for_caregiver': 'Enkawltu kaihhruaina',
      'voice_feedback_prompt': 'Sawi turin mic hmet rawh',
      'voice_input_tip': 'Sawi turin mic hmet la a hnuai lamah ziak rawh',
      'voice_listening': 'I aw ngaithlak mek a ni...',
      'voice_recorded': 'Aw hi hlawhtling taka chhinchhiah a ni',
      'non_medical_disclaimer': 'Hei hi ni tin inkawmhona mai a ni, damdawi lam endikna a ni lo.',
      'caregiver_welcome_title': 'Profile siam rawh',
      'caregiver_welcome_badge': 'Minute 5 enkawltu buatsaihna',
      'caregiver_welcome_desc': 'I mi duhtak tan thlamuanpuiawm leh nuam ber turin minute 5 chhungin profile siam rawh.',
      'caregiver_why_title': 'Hemi hian a tanpui dan turte:',
      'caregiver_why_1': 'Hla duh zawng, hmun leh chaw tui tih zawng a thlang.',
      'caregiver_why_2': 'Thlamuang tak leh muang marin a tihtheih.',
      'caregiver_why_3': 'Ni tin thiltih leh doctor thurawn a vawng tha.',
      'start_profile_btn': 'Profile siam tan rawh',
      'load_demo_btn': 'Demo Profile hmang rawh (Bonti Baruah)',
      'part_1_title': 'Bung 1 / 3: Hriattirna Tlangpui',
      'part_1_desc': 'Tu nge kan enkawl dawn? Sawi la emaw ziak rawh.',
      'part_2_title': 'Bung 2 / 3: Theihna, Duh zawng leh Thlirna',
      'part_2_desc': 'Hla, chaw, nuam tih zawng leh thlamuanna.',
      'part_3_title': 'Bung 3 / 3: Ni tin Hun bi leh Doctor Thurawn',
      'part_3_desc': 'Ni tin hun bi, doctor thurawn leh aw hmanga hriattirna.',
      'profile_complete_title': 'Hmangaihna nen Profile siam a ni ta!',
      'profile_complete_subtitle': 'Vawiin hun nuam tan turin kan inpeih ta e.',
      'start_todays_journey': 'Vawiin hun tan rawh',
      'fetching_profile': 'Chibai! Vawiin hun tur lak mek a ni...',
      'patient_name_label': 'Hming koh duh zawng',
      'hometown_label': 'Khua emaw chenna hmun',
      'doctor_advises_label': 'Doctor thurawn leh kaihhruaina',
      'routines_label': 'Ni tin hun bi leh thlamuan hun',
      'caregiver_obs_label': 'Enkawltu hmuh dan leh thlamuanna',
      'domain_memory': 'Hriat rengna',
      'domain_attention': 'Ngaihtuahna',
      'domain_language': 'Inbiakna',
      'domain_executive': 'Ruahmanna',
      'domain_orientation': 'Vawiin leh Hmun',
      'domain_visuospatial': 'Entawn leh Rem',
      'cg_domain_memory': 'Hriat reng leh Hriatfiah',
      'cg_domain_attention': 'Ngaihven leh Thlir',
      'cg_domain_language': 'Tawng leh Inbiakpawhna',
      'cg_domain_executive': 'Thiltih theihna',
      'cg_domain_orientation': 'Hun leh Hmun hriatna',
      'cg_domain_visuospatial': 'Hmun leh Mizia hriatna',
      'memory_vault': 'Hriatrengna Bawm',
      'add_memory': 'Hriatrengna thar dah rawh',
      'system_states': 'System leh AI Dinhmun',
      'session_finish': 'Vawiin atan tawk rawh se',
      'continue_button': 'Kal zel rawh',
      'back_button': 'Him takin kir rawh',
    },
  };

  static String get(String key) {
    return _localizedValues[currentLanguage]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static Future<void> loadSavedLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final saved = prefs.getString(_prefLanguageKey);
      if (saved != null && _localizedValues.containsKey(saved)) {
        currentLanguage = saved;
        languageNotifier.value = saved;
      }
    } catch (e) {
      debugPrint('Error loading saved language: $e');
    }
  }

  static void setLanguage(String langCode) {
    if (_localizedValues.containsKey(langCode)) {
      currentLanguage = langCode;
      languageNotifier.value = langCode;
      SharedPreferences.getInstance().then((prefs) {
        prefs.setString(_prefLanguageKey, langCode);
      }).catchError((e) {
        debugPrint('Error saving language preference: $e');
      });
    }
  }
}
