import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Multilingual string dictionaries supporting English, Hindi, and Assamese.
class AppStrings {
  AppStrings._();

  static const String _prefLanguageKey = 'selected_language';
  static String currentLanguage = 'en'; // 'en', 'hi', 'as'
  static final ValueNotifier<String> languageNotifier = ValueNotifier<String>('en');

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Smriti',
      'tagline': 'Gentle care, every day',
      'start_button': 'Start',
      'role_caregiver': 'I am a Caregiver',
      'role_patient': 'Continue as Patient',
      'offline_note': 'Works completely offline. Activity data stays private.',
      'caregiver_present_q': 'Is a caregiver with you right now?',
      'yes_together': 'Yes, we are together',
      'no_independent': 'No, independent session',
      'todays_journey': "Today's Gentle Journey",
      'daily_greeting': 'Welcome back. Let us spend a peaceful moment together.',
      'spoken_help': 'Listen to instruction',
      'pause': 'Pause',
      'resume': 'Resume',
      'take_time': "That's okay. We can take our time.",
      'gentle_success': 'Wonderful effort today!',
      'together_mode': 'Together Mode',
      'hint_for_caregiver': 'Caregiver Prompt Guide',
      'voice_feedback_prompt': 'Tap microphone to speak your observation',
      'voice_input_tip': 'Tap microphone to speak or type manually below',
      'voice_listening': 'Listening to your voice... (tap to finish)',
      'voice_recorded': 'Voice message recorded successfully',
      'non_medical_disclaimer': 'These are supportive engagement trends, not a medical diagnosis or staging assessment.',
      'caregiver_welcome_title': 'Create a Profile',
      'caregiver_welcome_badge': '5 minutes ❤️',
      'caregiver_welcome_desc': 'You know your loved one best. Tell us a little about them, and we will make every moment in this app feel familiar and comforting.',
      'caregiver_why_title': 'What this helps with:',
      'caregiver_why_1': 'Their favourite music, places, and foods will feel familiar.',
      'caregiver_why_2': 'Activities will move at their own comfortable pace.',
      'caregiver_why_3': 'Doctor notes and daily routines are always close by.',
      'start_profile_btn': 'Create Profile',
      'load_demo_btn': 'Load Demo Profile (Bonti Baruah)',
      'part_1_title': 'Part 1 of 3: General Information',
      'part_1_desc': 'Who are we caring for? Speak or type their details.',
      'part_2_title': 'Part 2 of 3: Abilities, Preferences & Observations',
      'part_2_desc': 'Sensory comforts, beloved music, foods, and calming triggers.',
      'part_3_title': "Part 3 of 3: Daily Routines & Doctor's Advises",
      'part_3_desc': 'Daily rhythm anchors, doctor recommendations, and voice reminders.',
      'profile_complete_title': 'Profile Created with Love!',
      'profile_complete_subtitle': "We are ready to begin today's peaceful journey.",
      'start_todays_journey': "Start Today's Journey",
      'fetching_profile': 'Welcome back! Fetching personalized journey...',
      'patient_name_label': 'Preferred Name or Nickname',
      'hometown_label': 'Familiar Hometown or Region',
      'doctor_advises_label': "Doctor's Advises & Clinician Notes",
      'routines_label': 'Daily Routines & Peaceful Anchors',
      'caregiver_obs_label': 'Caregiver Observations & Calming Anchors',
      'domain_memory': 'Remember',
      'domain_attention': 'Notice',
      'domain_language': 'Talk',
      'domain_executive': 'Plan & Sort',
      'domain_orientation': 'Today & Places',
      'domain_visuospatial': 'Explore & Match',
      'cg_domain_memory': 'Memory & Recognition',
      'cg_domain_attention': 'Attention & Focus',
      'cg_domain_language': 'Language & Communication',
      'cg_domain_executive': 'Executive Function',
      'cg_domain_orientation': 'Orientation & Context',
      'cg_domain_visuospatial': 'Visuospatial Skills',
      'memory_vault': 'Personal Memory Space',
      'add_memory': 'Add a Memory',
      'system_states': 'System & AI States',
      'session_finish': 'Finish Session for Today',
      'continue_button': 'Continue',
      'back_button': 'Go Back Safely',
    },
    'hi': {
      'app_title': 'स्मृति साथी',
      'tagline': 'सद्भाव, अपनत्व और दैनिक संज्ञान सहयोग',
      'start_button': 'शुरू करें',
      'role_caregiver': 'मैं देखभालकर्ता (केयरगिवर) हूँ',
      'role_patient': 'मरीज के रूप में आगे बढ़ें',
      'offline_note': 'बिना इंटरनेट के भी पूर्णतः सुरक्षित चलता है।',
      'caregiver_present_q': 'क्या देखभालकर्ता अभी आपके साथ हैं?',
      'yes_together': 'हाँ, हम साथ हैं',
      'no_independent': 'नहीं, अकेले कर रहे हैं',
      'todays_journey': 'आज का शांत सफर',
      'daily_greeting': 'नमस्ते! आइए मिलकर कुछ सुखद पल बिताएं।',
      'spoken_help': 'निर्देश सुनें',
      'pause': 'विराम',
      'resume': 'पुनः शुरू करें',
      'take_time': 'कोई जल्दी नहीं है, आराम से करें।',
      'gentle_success': 'बहुत सुंदर प्रयास!',
      'together_mode': 'साथ-साथ मोड',
      'hint_for_caregiver': 'केयरगिवर संकेत मार्गदर्शिका',
      'voice_feedback_prompt': 'माइक दबाकर अपनी बात रिकॉर्ड करें',
      'voice_input_tip': 'बोलने के लिए माइक दबाएं, या नीचे टाइप करें',
      'voice_listening': 'आपकी आवाज सुनी जा रही है... (पूरा होने पर टैप करें)',
      'voice_recorded': 'वॉइस संदेश सफलतापूर्वक रिकॉर्ड हुआ',
      'non_medical_disclaimer': 'यह केवल दैनिक गतिविधि और जुड़ाव का ब्योरा है, कोई चिकित्सकीय निदान नहीं।',
      'caregiver_welcome_title': 'प्रोफाइल बनाएं',
      'caregiver_welcome_badge': 'केयरगिवर सेटअप • केवल 5 मिनट',
      'caregiver_welcome_desc': 'परिवार के देखभालकर्ता द्वारा केवल 5 मिनट में प्रोफाइल तैयार करें ताकि आपके प्रियजन को सबसे सहज, सुरक्षित और आनंददायक अनुभव मिले।',
      'caregiver_why_title': 'यह आपके प्रियजन की कैसे मदद करता है:',
      'caregiver_why_1': 'पसंदीदा संगीत, तस्वीरें और सांस्कृतिक यादों को जोड़ता है।',
      'caregiver_why_2': 'बिना किसी तनाव के सोचने और छूने की गति को आसान बनाता है।',
      'caregiver_why_3': 'दिनचर्या और डॉक्टर की सलाह को सुरक्षित रखता है।',
      'start_profile_btn': '5 मिनट में प्रोफाइल शुरू करें',
      'load_demo_btn': 'डेमो प्रोफाइल लोड करें (बोंती बरुआ)',
      'part_1_title': 'भाग 1 / 3: सामान्य जानकारी',
      'part_1_desc': 'हम किसकी देखभाल कर रहे हैं? बोलें या टाइप करें।',
      'part_2_title': 'भाग 2 / 3: क्षमता, पसंद और अवलोकन',
      'part_2_desc': 'सहजता, पसंदीदा संगीत, भोजन और सुकून देने वाली बातें।',
      'part_3_title': 'भाग 3 / 3: दिनचर्या और डॉक्टर की सलाह',
      'part_3_desc': 'दैनिक दिनचर्या, डॉक्टर के सुझाव और वॉइस रिमाइंडर्स।',
      'profile_complete_title': 'प्रोफाइल प्यार से तैयार है!',
      'profile_complete_subtitle': 'हम आज का शांतिपूर्ण सफर शुरू करने के लिए तैयार हैं।',
      'start_todays_journey': 'आज का सफर शुरू करें',
      'fetching_profile': 'नमस्ते! आपका आज का सफर लोड हो रहा है...',
      'patient_name_label': 'पसंदीदा नाम या उपनाम',
      'hometown_label': 'परिचित गृहनगर या क्षेत्र',
      'doctor_advises_label': 'डॉक्टर की सलाह और निर्देश',
      'routines_label': 'दैनिक दिनचर्या और सुकून भरे पल',
      'caregiver_obs_label': 'केयरगिवर के अवलोकन और शांत करने वाले उपाय',
      'domain_memory': 'याद रखें',
      'domain_attention': 'ध्यान दें',
      'domain_language': 'बातचीत',
      'domain_executive': 'क्रम और व्यवस्था',
      'domain_orientation': 'आज का दिन और स्थान',
      'domain_visuospatial': 'मिलान और पहचान',
      'cg_domain_memory': 'स्मृति और पहचान',
      'cg_domain_attention': 'ध्यान और एकाग्रता',
      'cg_domain_language': 'भाषा और संवाद',
      'cg_domain_executive': 'कार्यकारी क्षमता',
      'cg_domain_orientation': 'समय व स्थान बोध',
      'cg_domain_visuospatial': 'दृश्य-स्थानिक कौशल',
      'memory_vault': 'व्यक्तिगत स्मृति संदूक',
      'add_memory': 'नई स्मृति जोड़ें',
      'system_states': 'सिस्टम और एआई स्थितियां',
      'session_finish': 'आज का सत्र समाप्त करें',
      'continue_button': 'आगे बढ़ें',
      'back_button': 'सुरक्षित पीछे जाएं',
    },
    'as': {
      'app_title': 'স্মৃতি সংগী',
      'tagline': 'মৰমৰ সান্নিধ্য আৰু দৈনন্দিন মানসিক সঁহাৰি',
      'start_button': 'আৰম্ভ কৰক',
      'role_caregiver': 'মই এজন শুশ্ৰূষাকাৰী (Caregiver)',
      'role_patient': 'অংশগ্ৰহণকাৰী হিচাপে আৰম্ভ কৰক',
      'offline_note': 'ইণ্টাৰনেট অবিহনে সম্পূৰ্ণ কাম কৰে। সকলো তথ্য নিজৰ ডিভাইচতে সুৰক্ষিত।',
      'caregiver_present_q': 'শুশ্ৰূষাকাৰী আপোনাৰ লগত উপস্থিত আছেনে?',
      'yes_together': 'হয়, আমি একেলগে আছোঁ',
      'no_independent': 'নহয়, অকলেই কৰিম',
      'todays_journey': 'আজিৰ শান্ত যাত্ৰা',
      'daily_greeting': 'স্বাগতম! আহক আমি একেলগে কেইটামান শান্তিপূৰ্ণ মুহূৰ্ত কটাওঁ।',
      'spoken_help': 'নিৰ্দেশনা শুনক',
      'pause': 'ৰওক',
      'resume': 'পুনৰ আৰম্ভ কৰক',
      'take_time': 'কোনো খৰখেদা নাই, শান্তভাৱে কৰক।',
      'gentle_success': 'বৰ সুন্দৰ প্ৰয়াস!',
      'together_mode': 'একত্ৰে খেলাৰ সুবিধা',
      'hint_for_caregiver': 'শুশ্ৰূষাকাৰীৰ বাবে সহায়ক ইঙ্গিত',
      'voice_feedback_prompt': 'কথা ক\'বলৈ মাইক্ৰ\'ফন স্পৰ্শ কৰক',
      'voice_input_tip': 'কথা ক\'বলৈ মাইক্ৰ\'ফন স্পৰ্শ কৰক বা লিখক',
      'voice_listening': 'আপোনাৰ কথা শুনা হৈছে... (শেষ হ\'লে স্পৰ্শ কৰক)',
      'voice_recorded': 'কণ্ঠ বাৰ্তা সফলতাৰে সংৰক্ষণ হ\'ল',
      'non_medical_disclaimer': 'এইয়া কেৱল দৈনন্দিন সঁহাৰি আৰু সংযোগৰ তথ্য, কোনো চিকিৎসাজনিত পৰীক্ষা নহয়।',
      'caregiver_welcome_title': 'এটা প্ৰোফাইল সৃষ্টি কৰক',
      'caregiver_welcome_badge': 'শুশ্ৰূষাকাৰী প্ৰস্তুতি • মাত্ৰ ৫ মিনিট',
      'caregiver_welcome_desc': 'পৰিয়ালৰ শুশ্ৰূষাকাৰীৰ দ্বাৰা মাত্ৰ ৫ মিনিটতে প্ৰোফাইল প্ৰস্তুত কৰক যাতে আপোনাৰ আপোনজনৰ বাবে সকলোতকেই শান্ত, সুৰক্ষিত আৰু আনন্দদায়ক অভিজ্ঞতা প্ৰদান কৰিব পাৰি।',
      'caregiver_why_title': 'ই আপোনাৰ আপোনজনক কেনেদৰে সহায় কৰিব:',
      'caregiver_why_1': 'অসম আৰু উত্তৰ-পূবৰ মৰমৰ গীত, ছবি আৰু স্মৃতিৰ সৈতে সংযোগ কৰে।',
      'caregiver_why_2': 'কোনো মানসিক চাপ নোহোৱাকৈ সহজ আৰু শান্ত গতিত খেলাৰ সুবিধা দিয়ে।',
      'caregiver_why_3': 'দৈনন্দিন নীতি-নিয়ম আৰু ডাক্তৰৰ পৰামৰ্শ অফলাইনত সুৰক্ষিত ৰাখে।',
      'start_profile_btn': '৫ মিনিটৰ প্ৰোফাইল আৰম্ভ কৰক',
      'load_demo_btn': 'ডেমো প্ৰোফাইল ব্যৱহাৰ কৰক (বন্টি বৰুৱা)',
      'part_1_title': 'ভাগ ১ / ৩: সাধাৰণ তথ্য',
      'part_1_desc': 'আমি কাৰ যত্ন লৈছোঁ? কথা কওক বা লিখি জনাওক।',
      'part_2_title': 'ভাগ ২ / ৩: ক্ষমতা, পছন্দ আৰু লক্ষ্যণ',
      'part_2_desc': 'প্ৰিয় সংগীত, খাদ্য, শান্তিপূৰ্ণ অনুভৱ আৰু যত্নৰ লক্ষ্যণ।',
      'part_3_title': 'ভাগ ৩ / ৩: দৈনন্দিন নিয়ম আৰু চিকিৎসকৰ পৰামৰ্শ',
      'part_3_desc': 'দৈনন্দিন ৰীতি-নীতি, ডাক্তৰৰ দিহা আৰু কণ্ঠ স্মাৰক।',
      'profile_complete_title': 'মৰমেৰে প্ৰোফাইল প্ৰস্তুত হ\'ল!',
      'profile_complete_subtitle': 'আমি আজিৰ শান্ত যাত্ৰা আৰম্ভ কৰিবলৈ সাজু।',
      'start_todays_journey': 'আজিৰ যাত্ৰা আৰম্ভ কৰক',
      'fetching_profile': 'স্বাগতম! আপোনাৰ বাবে আজিৰ যাত্ৰা প্ৰস্তুত কৰা হৈছে...',
      'patient_name_label': 'মৰমৰ নাম বা উপনাম',
      'hometown_label': 'চিনাকি গাঁও/চহৰ বা অঞ্চল',
      'doctor_advises_label': 'চিকিৎসকৰ পৰামৰ্শ আৰু দিহা',
      'routines_label': 'দৈনন্দিন নিয়ম আৰু শান্তিপূৰ্ণ সময়',
      'caregiver_obs_label': 'শুশ্ৰূষাকাৰীৰ লক্ষ্যণ আৰু শান্ত কৰাৰ উপায়',
      'domain_memory': 'মনত পেলাওক',
      'domain_attention': 'মনোযোগ দিয়ক',
      'domain_language': 'কথোপকথন',
      'domain_executive': 'সজাই তোলক',
      'domain_orientation': 'আজিৰ দিন আৰু পৰিৱেশ',
      'domain_visuospatial': 'আকৃতি আৰু সন্ধান',
      'cg_domain_memory': 'স্মৃতি আৰু চিনাক্তকৰণ',
      'cg_domain_attention': 'মনোযোগ আৰু দৃষ্টি',
      'cg_domain_language': 'ভাষা আৰু যোগাযোগ',
      'cg_domain_executive': 'কাৰ্য্যকৰী ক্ষমতা',
      'cg_domain_orientation': 'সময় আৰু স্থানবোধ',
      'cg_domain_visuospatial': 'স্থান আৰু দৃশ্যগত দক্ষতা',
      'memory_vault': 'ব্যক্তিগত স্মৃতি ভঁৰাল',
      'add_memory': 'নতুন স্মৃতি যোগ কৰক',
      'system_states': 'ছিষ্টেম আৰু এআই অৱস্থা',
      'session_finish': 'আজিৰ সত্ৰ সমাপ্ত কৰক',
      'continue_button': 'আগবাঢ়ক',
      'back_button': 'সুৰক্ষিতভাৱে পিছলৈ যাওক',
    },
  };

  static String get(String key) {
    return _localizedValues[currentLanguage]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  static Future<void> loadSavedLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final saved = prefs.getString(_prefLanguageKey);
      if (saved != null && _localizedValues.containsKey(saved)) {
        currentLanguage = saved;
        languageNotifier.value = saved;
      }
    } catch (e) {
      debugPrint('Error loading saved language: $e');
    }
  }

  static void setLanguage(String langCode) {
    if (_localizedValues.containsKey(langCode)) {
      currentLanguage = langCode;
      languageNotifier.value = langCode;
      SharedPreferences.getInstance().then((prefs) {
        prefs.setString(_prefLanguageKey, langCode);
      }).catchError((e) {
        debugPrint('Error saving language preference: $e');
      });
    }
  }
}
